language: cpp
compiler: clang
sudo: false

# Blacklist
#branches:
#  only:
#    - master

# Environment variables
#env:
#  global:
#    - GH_REPO_NAME: otus_cpp_04
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
#    - GH_REPO_REF: github.com/evgenykol/otus_cpp_04.git

# Install dependencies
addons:
  apt:
    packages:
      - libboost-test-dev -y
      - doxygen
      - graphviz

# Может объединить с тем что повыше?
#before_script:
#  - sudo apt-get install libboost-test-dev -y

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen $TRAVIS_BUILD_DIR/Doxyfile

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_print-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uevgenykol:$BINTRAY_API_KEY "https://api.bintray.com/content/evgenykol/otus_cpp_01/ip_print/$TRAVIS_BUILD_NUMBER/ip_print-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  provider: pages
  skip-cleanup: true
  github-token: $GH_REPO_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: html
  on:
    branch: master

# Generate and deploy documentation
#after_success:
#  - cd $TRAVIS_BUILD_DIR
#  - chmod +x generateDocumentationAndDeploy.sh
#  - ./generateDocumentationAndDeploy.sh